version: '3'
services:
    api:
        build: .
        ports:
            - '8080:80'
        volumes:
            - './:/var/www/app:rw'
        links:
            - db
        depends_on:
            - db

    db:
        image: mysql:8.0.26
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: meditation_app
            MYSQL_USER: meditation_app_user
            MYSQL_PASSWORD: meditation_app_password
        volumes:
            - db:/var/lib/mysql

volumes:
    db:
